### ISSUE TITLE
BUG - MT2652 - Parameters are incorrect in app.json - device not configured properly

### ISSUE THREAD

**Issue by djanssen1** [athombv/com.devolo#1]
Hi there,

I tried to use a MT2652 but got lots of issues. After some debugging I found parameters are wrongly set because they are wrong in app.json. Issues I faced where related to central scene and buttons

As I'm not a real developer I will not make the fixes myself. If you look at the Z-wave me app you can find the correct parameters as this device is same as the Z-wave.ME. I have that one as well and that works fine.

"manufacturerId": 340,
			"productTypeId": 256,
			"productId": 257,

**Comment by RobinBol** [comment]
Fixed by: https://github.com/athombv/com.devolo/pull/2
